In [7]:
import category_encoders as ce
import pandas as pd
train_df=pd.DataFrame({"Degree":["High School","Masters","Phd","Diploma","High School","Phd","Bachalors","Bachalors"]})
train_df

        Degree
0  High School
1      Masters
2          Phd
3      Diploma
4  High School
5          Phd
6    Bachalors
7    Bachalors

In [8]:
encoder=ce.OrdinalEncoder(cols=['Degree'],return_df=True,mapping=[{"col":"Degree","mapping":{"None":0,"High School":1,
                                                                                             "Masters":2,"Phd":3,"Bachalors":4,
                                                                                              "Diploma":5}}])


train_df

        Degree
0  High School
1      Masters
2          Phd
3      Diploma
4  High School
5          Phd
6    Bachalors
7    Bachalors

In [11]:
df=encoder.fit_transform(train_df)
df

   Degree
0       1
1       2
2       3
3       5
4       1
5       3
6       4
7       4

### One Hot encoding

In [12]:
import category_encoders as ce
import pandas as pd

In [22]:
data=pd.DataFrame({"City":["Delhi","Mumbai","Hydrabad","Channai","Bangalore","Delhi","Hydrabad","Banglaore","Delhi"]})
data
data.shape

(9, 1)

In [27]:
encoder=ce.OneHotEncoder(cols="City",handle_unknown="return_nan",return_df=True,use_cat_names=True)
data

        City
0      Delhi
1     Mumbai
2   Hydrabad
3    Channai
4  Bangalore
5      Delhi
6   Hydrabad
7  Banglaore
8      Delhi

In [28]:
df1=encoder.fit_transform(data)
df1

,City_Delhi,City_Mumbai,City_Hydrabad,City_Channai,City_Bangalore,City_Banglaore
0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,1.0
8,1.0,0.0,0.0,0.0,0.0,0.0

In [29]:
import category_encoders as ce
import pandas as pd
import numpy as np

In [32]:
headers=["symboling","normalized_losses","make","Fuel_type","asoiration","num_doors",
        
 "body_style","deive_wheels","engine_location","wheel_base",
        "length","width","height","curb_weight","engine_type","Num_cylinders",'engine_size',"fuel_system",
       "bore","Stroke","comprssion_ratio","horsepower","peak_rpm","city_mpg","highway_mpg","price" ]

df=pd.read_csv("imports-85.data",header=None,names=headers,na_values="?")
df.head(44)

,symboling,normalized_losses,make,Fuel_type,asoiration,num_doors,body_style,deive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,Stroke,comprssion_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.00,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.00,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.00,115.0,5500.0,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,15250.0
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,18920.0
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.30,140.0,5500.0,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.00,160.0,5500.0,16,22,NaN
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101.0,5800.0,23,29,16430.0
11,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101.0,5800.0,23,29,16925.0
12,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,21,28,20970.0
13,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,16,22,30760.0
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,16,22,41315.0
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,15,20,36880.0
18,2,121.0,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48.0,5100.0,47,53,5151.0
19,1,98.0,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,6295.0
20,0,81.0,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,6575.0
21,1,118.0,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68.0,5500.0,37,41,5572.0
22,1,118.0,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6377.0
23,1,118.0,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102.0,5500.0,24,30,7957.0
24,1,148.0,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6229.0
25,1,148.0,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6692.0
26,1,148.0,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,7609.0
27,1,148.0,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102.0,5500.0,24,30,8558.0
28,-1,110.0,dodge,gas,std,four,wagon,fwd,front,103.3,...,122,2bbl,3.34,3.46,8.50,88.0,5000.0,24,30,8921.0
29,3,145.0,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.60,3.90,7.00,145.0,5000.0,19,24,12964.0
30,2,137.0,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.60,58.0,4800.0,49,54,6479.0
31,2,137.0,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,31,38,6855.0
32,1,101.0,honda,gas,std,two,hatchback,fwd,front,93.7,...,79,1bbl,2.91,3.07,10.10,60.0,5500.0,38,42,5399.0
33,1,101.0,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,30,34,6529.0
34,1,101.0,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,30,34,7129.0
35,0,110.0,honda,gas,std,four,sedan,fwd,front,96.5,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,30,34,7295.0
36,0,78.0,honda,gas,std,four,wagon,fwd,front,96.5,...,92,1bbl,2.92,3.41,9.20,76.0,6000.0,30,34,7295.0
37,0,106.0,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,7895.0
38,0,106.0,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,9095.0
39,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,8845.0
40,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,10295.0
41,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.00,101.0,5800.0,24,28,12945.0
42,1,107.0,honda,gas,std,two,sedan,fwd,front,96.5,...,110,2bbl,3.15,3.58,9.10,100.0,5500.0,25,31,10345.0
43,0,NaN,isuzu,gas,std,four,sedan,rwd,front,94.3,...,111,2bbl,3.31,3.23,8.50,78.0,4800.0,24,29,6785.0

In [33]:
df.dtypes

symboling              int64
normalized_losses    float64
make                  object
Fuel_type             object
asoiration            object
num_doors             object
body_style            object
deive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
Num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
Stroke               float64
comprssion_ratio     float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [37]:
obj_df=df.select_dtypes(include=["object"].copy())
obj_df

,make,Fuel_type,asoiration,num_doors,body_style,deive_wheels,engine_location,engine_type,Num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi
...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
201,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
202,volvo,gas,std,four,sedan,rwd,front,ohcv,six,mpfi
203,volvo,diesel,turbo,four,sedan,rwd,front,ohc,six,idi
204,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi

In [38]:
obj_df.shape

(205, 10)

In [41]:
obj_df.head(30)
obj_df[obj_df.isnull().any(axis=1)]

,make,Fuel_type,asoiration,num_doors,body_style,deive_wheels,engine_location,engine_type,Num_cylinders,fuel_system
27,dodge,gas,turbo,NaN,sedan,fwd,front,ohc,four,mpfi
63,mazda,diesel,std,NaN,sedan,fwd,front,ohc,four,idi

In [43]:
obj_df["num_doors"].value_counts()

num_doors
four    114
two      89
Name: count, dtype: int64

In [50]:
obj_df=obj_df.fillna({"num_doors":"four"})
obj_df.head(30)

,make,Fuel_type,asoiration,num_doors,body_style,deive_wheels,engine_location,engine_type,Num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi
5,audi,gas,std,two,sedan,fwd,front,ohc,five,mpfi
6,audi,gas,std,four,sedan,fwd,front,ohc,five,mpfi
7,audi,gas,std,four,wagon,fwd,front,ohc,five,mpfi
8,audi,gas,turbo,four,sedan,fwd,front,ohc,five,mpfi
9,audi,gas,turbo,two,hatchback,4wd,front,ohc,five,mpfi
10,bmw,gas,std,two,sedan,rwd,front,ohc,four,mpfi
11,bmw,gas,std,four,sedan,rwd,front,ohc,four,mpfi
12,bmw,gas,std,two,sedan,rwd,front,ohc,six,mpfi
13,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
14,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
15,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
16,bmw,gas,std,two,sedan,rwd,front,ohc,six,mpfi
17,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
18,chevrolet,gas,std,two,hatchback,fwd,front,l,three,2bbl
19,chevrolet,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
20,chevrolet,gas,std,four,sedan,fwd,front,ohc,four,2bbl
21,dodge,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
22,dodge,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
23,dodge,gas,turbo,two,hatchback,fwd,front,ohc,four,mpfi
24,dodge,gas,std,four,hatchback,fwd,front,ohc,four,2bbl
25,dodge,gas,std,four,sedan,fwd,front,ohc,four,2bbl
26,dodge,gas,std,four,sedan,fwd,front,ohc,four,2bbl
27,dodge,gas,turbo,four,sedan,fwd,front,ohc,four,mpfi
28,dodge,gas,std,four,wagon,fwd,front,ohc,four,2bbl
29,dodge,gas,turbo,two,hatchback,fwd,front,ohc,four,mfi

In [57]:
obj_df["body_style_cat"]=obj_df["body_style"].cat.codes
obj_df.head()

AttributeError: Can only use .cat accessor with a 'category' dtype